apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bancx-gitops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Siya360/gitops-argocd-k3s-hello.git
    targetRevision: feature/bancx-gitops-simulation
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
