apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Siya360/gitops-argocd-k3s-hello.git
    targetRevision: feature/bancx-gitops-simulation
    path: automation
  destination:
    server: https://kubernetes.default.svc
    namespace: automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
